#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mongo-database-tools -a -d /usr/share/doc/mongo-database-tools ]; then
    ln -sf ../share/doc/mongo-database-tools /usr/doc/mongo-database-tools
  fi
fi
