# We use the github backend for nearly everything we can for two reasons. One is consistency: this
# way all developers compile Go packages with the same versions. The other is speed: downloading
# pre-built binaries from GitHub is faster than compiling from source. In many cases these tools
# are available in the mise registry with multiple backends, so spelling out "github:..." ensures
# we use the github backend.

[tools]
# Go and Go tools
go = "1.26.4"
"go:golang.org/x/tools/cmd/goimports" = "0.29.0"
"go:golang.org/x/tools/gopls" = "0.21.1"
"github:golangci/golangci-lint" = "2.12.2"
"github:securego/gosec" = "2.27.1"
"github:segmentio/golines" = "0.12.2"
"github:houseabsolute/precious" = "0.10.2"
"github:crate-ci/typos" = "1.46.1"

# Node and npm tools
node = { version = "22.22.0", postinstall = "$MISE_TOOL_INSTALL_PATH/bin/npm install --loglevel verbose" }
"npm:eslint" = "8.57.0"
"npm:prettier" = "3.4.2"
"npm:github-codeowners" = "0.2.1"

[settings.node]
# We turn off GPG verification for node because it has been flaky in CI, and also requires a local
# GPG public key.
gpg_verify = false
