s3:
  bucket: c2c-testing-server-artifacts
  region: us-east-1
  serverBinariesPrefix: server-binaries
  resmokePrefix: resmoke

serverVersions:
  - version: "9.1-dsc"
    commit: 67d46e783fb535d6747dab3b2eb54bbaed6dba13 # 2026-09-16
    disagg: true
    resmoke: false
    platforms:
      - os: ubuntu2204
        arch: arm64
      - os: ubuntu2204
        arch: x86_64
