#!/usr/bin/env bash

# This script is intended to provide simplified setup for the benchmark
# harness in this PR. Here, $RESULTS_DIR corresponds to the Golang
# variable benchmarkDataRootDir -- the script uses the Mongo shell
# and mongodump to reproduce BSON files.

# It assumes that you have a MongoDB instance running over port 27017.
# That must be configured, i.e. with mlaunch, beforehand.

RESULTS_DIR="../results/"

for i in $(seq 0 5); do
    JS_FILE="d${i}.js"
    BSON_OUTPUT="dataset${i}.bson"

    echo "Creating: ${BSON_OUTPUT}"
    echo -e "\n\n"

    mongo < $JS_FILE
    mongodump
    mv dump/memtest/test.bson "${RESULTS_DIR}${BSON_OUTPUT}"

    rm -rf dump
done
