#!/bin/bash
# this file is copied from mongosync/etc/find-recent-python.sh

# This is based on some code generated by Gemini.

version_for_path() {
    "$1" -V 2>&1
}

# This turns the version into a number. "3.10.1" -> 30100001
numeric_version() {
    "$1" -c "import sys; vi = sys.version_info; print(vi.major * 1000000 + vi.minor * 1000 + vi.micro)"
}

want_version="3.10.0"
want_numeric="3010000"

python_path="python3"
found_python=""

if command -v "$python_path"; then
    path_version=$(version_for_path "$python_path")
    path_numeric=$(numeric_version "$python_path")

    if [ "$path_numeric" -ge "$want_numeric" ]; then
        echo "Using python3 binary in PATH with version = $path_version"
        found_python="true"
    fi
else
    echo "There is no python3 command in PATH"
fi

if [ -z "$found_python" ]; then
    toolchain_dir="/opt/mongodbtoolchain/v4/bin"
    python_path="$toolchain_dir/python3"
    if [ -f "$python_path" ]; then
        toolchain_version=$(version_for_path "$python_path")
        toolchain_numeric=$(numeric_version "$python_path")
        if [ "$toolchain_numeric" -ge "$want_numeric" ]; then
            echo "Using python3 binary at $python_path with version = $toolchain_version"
            found_python="true"

            PATH="$toolchain_dir:$PATH"
        fi
    fi
fi

if [ -z "$found_python" ]; then
    echo "Neither the python3 in PATH (if one exists) nor $python_path are >= $want_version"
    exit 1
fi
