#!/bin/bash
set -o errexit
set -o pipefail
set -o verbose

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=scripts/ci-env.sh
. "$SCRIPT_DIR/ci-env.sh"
# shellcheck source=scripts/functions.sh
. "$SCRIPT_DIR/functions.sh"

: "${TOOLS_GITHUB_TOKEN:?}"

# gh reads GH_TOKEN for both its own API calls and the git credential helper set up below.
export GH_TOKEN="${TOOLS_GITHUB_TOKEN}"
# Never fall back to an interactive credential prompt; there is no terminal to answer it.
export GIT_TERMINAL_PROMPT=0

REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CONFIG_PATH="${REPO_ROOT:?}/etc/mongodb-downloader-config.yaml"
ARTIFACTS_DIR="${REPO_ROOT:?}/etc"
ARTIFACTS_FILE="${ARTIFACTS_DIR:?}/mongodb-downloader-s3-artifacts.json"

BASE_BRANCH="master"
UPDATE_BRANCH="update-server-versions"
PR_TITLE="TOOLS-4392 Update Server versions we test against"
REPO_SLUG="mongodb/mongo-tools"

# The commit is attributed to this identity. A GitHub App token cannot look up its own bot login
# without an app JWT (which we do not have), so this is a plain tooling account, overridable by the
# task if we ever want it to match the app that opens the PR.
GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-mongo-tools-automation}"
GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-mongo-tools-automation@users.noreply.github.com}"

# gh is installed by mise (mise.gh.toml) and is not on PATH in CI, so route every call through mise
# exec. mise exec runs the real gh binary, so `gh auth setup-git` records an absolute path in the git
# credential helper.
gh() {
    mise exec github:cli/cli -- gh "$@"
}

# mongodb-downloader (a private repo) and gh live in their own mise config environments, mise.dsc.toml
# and mise.gh.toml, rather than in mise.toml, so they are only visible when MISE_ENV includes them.
# We only retry twice because the likely failure for the downloader is a token that cannot read the
# repo, which is not transient.
export MISE_ENV=dsc,gh
RETRY_FAILURES_BEFORE_BACKOFF=0 RETRY_FAILURES_BEFORE_HARD_FAIL=1 \
    retry mise install github:10gen/mongodb-downloader github:cli/cli

cd "$REPO_ROOT"

# Apply the update on top of the current tip of master, not on whatever commit this task happened to
# check out, so the PR is always against current master.
git fetch origin "$BASE_BRANCH"
git checkout -B "$UPDATE_BRANCH" "origin/${BASE_BRANCH}"

# update reprocesses every version in the config and rewrites
# etc/mongodb-downloader-s3-artifacts.json in place. The release-sourced entries re-resolve against
# the live downloads feed, so this picks up new patch releases; the commit-pinned entries (such as
# 9.1-dsc) do not change unless someone has bumped the pin.
mise exec github:10gen/mongodb-downloader -- mongodb-downloader update \
    --config "$CONFIG_PATH" \
    --output-dir "$ARTIFACTS_DIR"

if git diff --quiet -- "$CONFIG_PATH" "$ARTIFACTS_FILE"; then
    echo "Server versions are already current; nothing to do."
    exit 0
fi

git add -- "$CONFIG_PATH" "$ARTIFACTS_FILE"
git -c commit.gpgsign=false -c user.name="$GIT_AUTHOR_NAME" -c user.email="$GIT_AUTHOR_EMAIL" \
    commit --message "$PR_TITLE"

# git.get_project leaves origin pointing at a clone URL with the app's read token embedded, and git
# prefers that userinfo over a credential helper. Reset it to the plain URL and let gh's credential
# helper authenticate the push.
git remote set-url origin "https://github.com/${REPO_SLUG}.git"
gh auth setup-git
git push --force origin "HEAD:refs/heads/${UPDATE_BRANCH}"

# One long-lived branch means a run while the previous PR is still open updates that PR in place
# rather than opening a second one.
pr_body="$(
    cat <<EOF
This PR is generated by the weekly \`update-server-versions\` Evergreen task (TOOLS-4392).

It regenerates \`etc/mongodb-downloader-s3-artifacts.json\` by running \`mongodb-downloader update\`,
picking up new patch releases for the versions in \`etc/mongodb-downloader-config.yaml\`.

Evergreen task: https://spruce.mongodb.com/task/${EVG_TASK_ID:-unknown}
EOF
)"

pr_number="$(gh pr list --repo "$REPO_SLUG" --head "$UPDATE_BRANCH" --state open \
    --json number --jq '.[0].number // empty')"

if [ -n "$pr_number" ]; then
    printf '%s\n' "$pr_body" |
        gh pr edit "$pr_number" --repo "$REPO_SLUG" --title "$PR_TITLE" --body-file -
    echo "Updated pull request #${pr_number}."
else
    printf '%s\n' "$pr_body" |
        gh pr create --repo "$REPO_SLUG" --base "$BASE_BRANCH" --head "$UPDATE_BRANCH" \
            --title "$PR_TITLE" --body-file -
    echo "Opened a pull request for ${UPDATE_BRANCH}."
fi
