on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-alpine:
    runs-on: ubuntu-latest

    name: Build on Alpine/${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch:
          - armv6
          - armv7
          - aarch64
          - s390x
          - ppc64le

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: alpine_latest
          run: |
            unset CI
            apk add git go
            go run build.go build
