on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  qemu-alpine:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - i386
          - arm32v6
          - arm32v7
          - arm64v8
          - s390x

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - uses: uraimo/run-on-arch-action@v3
        with:
          arch: armv7
          run: apk add curl go && go run build.go build
#      - name: Get the qemu container
#        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#      - name: Run tests on ${{ matrix.platform }}
#        run: docker run --rm --interactive --mount type=bind,source=$(pwd),target=/host ${{ matrix.platform }}/alpine sh -c "apk add curl go; cd /host; go run build.go build"
