on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspi_4_bookworm:20231109
        commands: |
            sudo apt update
            sudo apt install libkrb5-dev
            go run build.go build
