on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            apt update
            apt install -y libkrb5-dev golang
            go version
            go run build.go build
