on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        base_image:
          - raspios_lite:latest
          - raspi_4_bookworm:20231109

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch tags (& history)

    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 500
        commands: |
            apt update
            apt install -y libkrb5-dev curl git

            eval "$(curl -sL https://raw.githubusercontent.com/urfave/gimme/main/gimme | GIMME_GO_VERSION=stable bash)"
            go version

            unset CI
            go run release/release.go get-version
            go run build.go build
